apiVersion: v1
kind: Service
metadata:
  labels:
    app: audio-file-processor-flower
  name: audio-file-processor-flower-service
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: audio-file-processor-flower
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5555
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audio-file-processor-flower-deployment
  namespace: default
  labels:
    app: audio-file-processor-flower
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: audio-file-processor-flower
  template:
    metadata:
      labels:
        app: audio-file-processor-flower
    spec:
      containers:
      - image: ADD_REGISTRY_URL/audio-file-processor-flower:latest
        imagePullPolicy: Always
        name: audio-file-processor-flower-container
        ports:
          - containerPort: 5555
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
  